export const posts = [
  {
    title: "New components for Once UI Blocks",
    description: "A roundup of the latest components and patterns we shipped.",
    author: {
      name: "Lorant",
      avatar: "/images/creators/lorant.jpg",
    },
    date: "2h ago",
    comments: 112,
    views: 1980,
    pinned: true,
    tag: "Announcement",
    participants: [
      { src: "/images/creators/lorant.jpg" },
      { src: "/images/creators/div.jpg" },
      { src: "/images/creators/suhaib.jpg" },
    ],
  },
  {
    title: "How do I override theme tokens?",
    description: "Looking for best practices to customize neutral and brand scales.",
    author: {
      name: "Div",
      avatar: "/images/creators/div.jpg",
    },
    date: "5h ago",
    comments: 18,
    views: 642,
    pinned: false,
    tag: "Question",
    participants: [
      { src: "/images/creators/div.jpg" },
      { src: "/images/creators/lorant.jpg" },
      { src: "/images/creators/light.jpg" },
    ],
  },
  {
    title: "Share your favorite layouts",
    description: "Post screenshots of your grid/layout experiments with Once UI.",
    author: {
      name: "Lorant",
      avatar: "/images/creators/lorant.jpg",
    },
    date: "Yesterday",
    comments: 54,
    views: 2390,
    pinned: false,
    tag: "Showcase",
    participants: [
      { src: "/images/creators/lorant.jpg" },
      { src: "/images/creators/vincent.jpg" },
      { src: "/images/creators/ryan.jpg" },
    ],
  },
  {
    title: "Request: Accessible Color Modes",
    description: "Proposal to add high-contrast presets and WCAG AA defaults.",
    author: {
      name: "Div",
      avatar: "/images/creators/div.jpg",
    },
    date: "2d ago",
    comments: 33,
    views: 1288,
    pinned: false,
    tag: "Feature",
    participants: [
      { src: "/images/creators/div.jpg" },
      { src: "/images/creators/issa.jpg" },
      { src: "/images/creators/evan.jpg" },
    ],
  },
  {
    title: "Bug: SegmentedControl focus ring",
    description: "Focus ring not visible on Windows high-contrast mode.",
    author: {
      name: "Lorant",
      avatar: "/images/creators/lorant.jpg",
    },
    date: "3d ago",
    comments: 7,
    views: 312,
    pinned: false,
    tag: "In Progress",
    participants: [{ src: "/images/creators/lorant.jpg" }, { src: "/images/creators/osmy.jpg" }],
  },
  {
    title: "Performance tips for large lists",
    description: "Virtualization strategies and micro-interaction perf wins.",
    author: {
      name: "Div",
      avatar: "/images/creators/div.jpg",
    },
    date: "Last week",
    comments: 76,
    views: 5194,
    pinned: false,
    tag: "Guide",
    participants: [
      { src: "/images/creators/div.jpg" },
      { src: "/images/creators/evan.jpg" },
      { src: "/images/creators/ryan.jpg" },
    ],
  },
  {
    title: "Docs: Getting started checklist",
    description: "A concise onboarding guide for new builders.",
    author: {
      name: "Suhaib King",
      avatar: "/images/creators/suhaib.jpg",
    },
    date: "1w ago",
    comments: 21,
    views: 1864,
    pinned: false,
    tag: "Docs",
    participants: [{ src: "/images/creators/suhaib.jpg" }, { src: "/images/creators/lorant.jpg" }],
  },
  {
    title: "Design critique thread",
    description: "Drop your component screenshots for async feedback.",
    author: {
      name: "Vincent",
      avatar: "/images/creators/vincent.jpg",
    },
    date: "1w ago",
    comments: 0,
    views: 2741,
    pinned: false,
    tag: "Community",
    participants: [],
  },
  {
    title: "Dark mode polish ideas",
    description: "Subtle glows, softened shadows, and better focus states.",
    author: {
      name: "light",
      avatar: "/images/creators/light.jpg",
    },
    date: "2w ago",
    comments: 29,
    views: 2017,
    pinned: false,
    tag: "Design",
    participants: [{ src: "/images/creators/light.jpg" }, { src: "/images/creators/div.jpg" }],
  },
  {
    title: "Fix: hover jitter on buttons",
    description: "Patched transform rounding and transition timing.",
    author: {
      name: "Osmy",
      avatar: "/images/creators/osmy.jpg",
    },
    date: "2w ago",
    comments: 12,
    views: 998,
    pinned: false,
    tag: "Changelog",
    participants: [{ src: "/images/creators/osmy.jpg" }, { src: "/images/creators/lorant.jpg" }],
  },
  {
    title: "Once UI + video editors?",
    description: "Any tips for motion-friendly component usage?",
    author: {
      name: "Texz",
      avatar: "/images/creators/texz.jpg",
    },
    date: "3w ago",
    comments: 9,
    views: 654,
    pinned: false,
    tag: "Discussion",
    participants: [{ src: "/images/creators/texz.jpg" }, { src: "/images/creators/victor.jpg" }],
  },
  {
    title: "Backend helpers for forms",
    description: "Patterns for handling optimistic updates and retries.",
    author: {
      name: "Ryan",
      avatar: "/images/creators/ryan.jpg",
    },
    date: "3w ago",
    comments: 23,
    views: 1432,
    pinned: false,
    tag: "Best Practice",
    participants: [{ src: "/images/creators/ryan.jpg" }, { src: "/images/creators/evan.jpg" }],
  },
  {
    title: "Supabase storage tips",
    description: "Public URLs, buckets, and cache headers that work well.",
    author: {
      name: "Issa",
      avatar: "/images/creators/issa.jpg",
    },
    date: "Last month",
    comments: 17,
    views: 1204,
    pinned: false,
    tag: "Guide",
    participants: [{ src: "/images/creators/issa.jpg" }, { src: "/images/creators/div.jpg" }],
  },
  {
    title: "Cursor workflows for builders",
    description: "Share your prompts and setups that speed things up.",
    author: {
      name: "Zaidh",
      avatar: "/images/creators/zaidh.jpg",
    },
    date: "Last month",
    comments: 31,
    views: 2109,
    pinned: false,
    tag: "Workflow",
    participants: [
      { src: "/images/creators/zaidh.jpg" },
      { src: "/images/creators/ryan.jpg" },
      { src: "/images/creators/evan.jpg" },
    ],
  },
  {
    title: "Game UI with Once",
    description: "Experimenting with HUDs and in-game menus.",
    author: {
      name: "Victor",
      avatar: "/images/creators/victor.jpg",
    },
    date: "Last month",
    comments: 0,
    views: 987,
    pinned: false,
    tag: "Showcase",
    participants: [],
  },
  {
    title: "TypeScript patterns we like",
    description: "Narrowing, discriminated unions, and exhaustiveness checks.",
    author: {
      name: "Evan",
      avatar: "/images/creators/evan.jpg",
    },
    date: "Last month",
    comments: 38,
    views: 2576,
    pinned: false,
    tag: "Engineering",
    participants: [
      { src: "/images/creators/evan.jpg" },
      { src: "/images/creators/ryan.jpg" },
      { src: "/images/creators/lorant.jpg" },
    ],
  },
];
