/**
 * Generates `src/icons/data.ts` — the SVG data for Once UI's built-in icons.
 *
 * Core used to take these from `react-icons` at runtime, which meant every
 * consumer installed 85M to render 54 icons that cost ~4 kB gzipped in the
 * bundle. The data is now inlined and react-icons is a devDependency, used
 * only here to regenerate it.
 *
 * The source sets are permissively licensed (see src/icons/ATTRIBUTION.md);
 * their notices ship with the package.
 *
 * Run: pnpm generate-icons   (after editing scripts/icon-manifest.json)
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const ROOT = path.dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, "icon-manifest.json"), "utf8"));
// react-icons does not export ./package.json, so resolve a family entry instead.
const reactIcons = path.dirname(path.dirname(require.resolve("react-icons/hi2")));

/** react-icons emits `export function Name (props) { return GenIcon({...})(props); };` */
function extract(family) {
  const src = fs.readFileSync(path.join(reactIcons, family, "index.mjs"), "utf8");
  const out = new Map();
  const re = /export function (\w+)\s*\(props\)\s*\{\s*return GenIcon\(/g;
  let m;
  while ((m = re.exec(src))) {
    const start = src.indexOf("(", re.lastIndex - 1);
    // Walk the JSON argument, which is a balanced object literal with no
    // strings containing braces — machine-generated, so this is safe.
    let depth = 0, i = start;
    for (; i < src.length; i++) {
      if (src[i] === "{") depth++;
      else if (src[i] === "}" && --depth === 0) { i++; break; }
    }
    out.set(m[1], JSON.parse(src.slice(src.indexOf("{", start), i)));
  }
  return out;
}

const families = new Map();
const entries = [];
for (const name of Object.keys(manifest).sort()) {
  const { family, symbol } = manifest[name];
  if (!families.has(family)) families.set(family, extract(family));
  const data = families.get(family).get(symbol);
  if (!data) throw new Error(`${symbol} not found in react-icons/${family}`);
  entries.push([name, data]);
}

const body = entries
  .map(([name, data]) => `  ${name}: ${JSON.stringify(data)},`)
  .join("\n");

fs.writeFileSync(
  path.join(ROOT, "..", "src", "icons", "data.ts"),
  `// Generated by scripts/generate-icons.mjs — do not edit by hand.
// Source sets and their licences: see ./ATTRIBUTION.md
import type { IconNode } from "./renderIcon";

export const iconData = {
${body}
} satisfies Record<string, IconNode>;
`,
);
console.log(`Generated ${entries.length} icons from ${[...families.keys()].sort().join(", ")}`);
