import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}", "./ai/**/*.{js,ts,jsx,tsx,mdx,json}"],
  theme: {
    screens: {
      xs: "640px",
      s: "768px",
      m: "1024px",
      l: "1200px",
      xl: "1440px",
    },
    borderRadius: {
      none: "0px",
      xs: "var(--radius-xs)",
      "xs-nest-4": "var(--radius-xs-nest-4)",
      "xs-nest-8": "var(--radius-xs-nest-8)",
      s: "var(--radius-s)",
      "s-nest-4": "var(--radius-s-nest-4)",
      "s-nest-8": "var(--radius-s-nest-8)",
      m: "var(--radius-m)",
      "m-nest-4": "var(--radius-m-nest-4)",
      "m-nest-8": "var(--radius-m-nest-8)",
      l: "var(--radius-l)",
      "l-nest-4": "var(--radius-l-nest-4)",
      "l-nest-8": "var(--radius-l-nest-8)",
      xl: "var(--radius-xl)",
      "xl-nest-4": "var(--radius-xl-nest-4)",
      "xl-nest-8": "var(--radius-xl-nest-8)",
      full: "var(--radius-full)",
    },
    extend: {
      colors: {
        page: {
          DEFAULT: "var(--page-background)",
          surface: "var(--surface-background)",
          border: "var(--surface-border)",
        },
        surface: {
          DEFAULT: "var(--surface-background)",
          border: "var(--surface-border)",
        },
        brand: {
          "background-weak": "var(--brand-background-weak)",
          "background-medium": "var(--brand-background-medium)",
          "background-strong": "var(--brand-background-strong)",
          "solid-weak": "var(--brand-solid-weak)",
          "solid-medium": "var(--brand-solid-medium)",
          "solid-strong": "var(--brand-solid-strong)",
          "on-solid-weak": "var(--brand-on-solid-weak)",
          "on-solid-medium": "var(--brand-on-solid-medium)",
          "on-solid-strong": "var(--brand-on-solid-strong)",
          "border-weak": "var(--brand-border-weak)",
          "border-medium": "var(--brand-border-medium)",
          "border-strong": "var(--brand-border-strong)",
          "alpha-weak": "var(--brand-alpha-weak)",
          "alpha-medium": "var(--brand-alpha-medium)",
          "alpha-strong": "var(--brand-alpha-strong)",
          "on-background-weak": "var(--brand-on-background-weak)",
          "on-background-medium": "var(--brand-on-background-medium)",
          "on-background-strong": "var(--brand-on-background-strong)",
        },
        neutral: {
          "background-weak": "var(--neutral-background-weak)",
          "background-medium": "var(--neutral-background-medium)",
          "background-strong": "var(--neutral-background-strong)",
          "solid-weak": "var(--neutral-solid-weak)",
          "solid-medium": "var(--neutral-solid-medium)",
          "solid-strong": "var(--neutral-solid-strong)",
          "on-solid-weak": "var(--neutral-on-solid-weak)",
          "on-solid-medium": "var(--neutral-on-solid-medium)",
          "on-solid-strong": "var(--neutral-on-solid-strong)",
          "border-weak": "var(--neutral-border-weak)",
          "border-medium": "var(--neutral-border-medium)",
          "border-strong": "var(--neutral-border-strong)",
          "alpha-weak": "var(--neutral-alpha-weak)",
          "alpha-medium": "var(--neutral-alpha-medium)",
          "alpha-strong": "var(--neutral-alpha-strong)",
          "on-background-weak": "var(--neutral-on-background-weak)",
          "on-background-medium": "var(--neutral-on-background-medium)",
          "on-background-strong": "var(--neutral-on-background-strong)",
        },
        accent: {
          "background-weak": "var(--accent-background-weak)",
          "background-medium": "var(--accent-background-medium)",
          "background-strong": "var(--accent-background-strong)",
          "solid-weak": "var(--accent-solid-weak)",
          "solid-medium": "var(--accent-solid-medium)",
          "solid-strong": "var(--accent-solid-strong)",
          "on-solid-weak": "var(--accent-on-solid-weak)",
          "on-solid-medium": "var(--accent-on-solid-medium)",
          "on-solid-strong": "var(--accent-on-solid-strong)",
          "border-weak": "var(--accent-border-weak)",
          "border-medium": "var(--accent-border-medium)",
          "border-strong": "var(--accent-border-strong)",
          "alpha-weak": "var(--accent-alpha-weak)",
          "alpha-medium": "var(--accent-alpha-medium)",
          "alpha-strong": "var(--accent-alpha-strong)",
          "on-background-weak": "var(--accent-on-background-weak)",
          "on-background-medium": "var(--accent-on-background-medium)",
          "on-background-strong": "var(--accent-on-background-strong)",
        },
        info: {
          "background-weak": "var(--info-background-weak)",
          "background-medium": "var(--info-background-medium)",
          "background-strong": "var(--info-background-strong)",
          "solid-weak": "var(--info-solid-weak)",
          "solid-medium": "var(--info-solid-medium)",
          "solid-strong": "var(--info-solid-strong)",
          "on-solid-weak": "var(--info-on-solid-weak)",
          "on-solid-medium": "var(--info-on-solid-medium)",
          "on-solid-strong": "var(--info-on-solid-strong)",
          "border-weak": "var(--info-border-weak)",
          "border-medium": "var(--info-border-medium)",
          "border-strong": "var(--info-border-strong)",
          "alpha-weak": "var(--info-alpha-weak)",
          "alpha-medium": "var(--info-alpha-medium)",
          "alpha-strong": "var(--info-alpha-strong)",
          "on-background-weak": "var(--info-on-background-weak)",
          "on-background-medium": "var(--info-on-background-medium)",
          "on-background-strong": "var(--info-on-background-strong)",
        },
        danger: {
          "background-weak": "var(--danger-background-weak)",
          "background-medium": "var(--danger-background-medium)",
          "background-strong": "var(--danger-background-strong)",
          "solid-weak": "var(--danger-solid-weak)",
          "solid-medium": "var(--danger-solid-medium)",
          "solid-strong": "var(--danger-solid-strong)",
          "on-solid-weak": "var(--danger-on-solid-weak)",
          "on-solid-medium": "var(--danger-on-solid-medium)",
          "on-solid-strong": "var(--danger-on-solid-strong)",
          "border-weak": "var(--danger-border-weak)",
          "border-medium": "var(--danger-border-medium)",
          "border-strong": "var(--danger-border-strong)",
          "alpha-weak": "var(--danger-alpha-weak)",
          "alpha-medium": "var(--danger-alpha-medium)",
          "alpha-strong": "var(--danger-alpha-strong)",
          "on-background-weak": "var(--danger-on-background-weak)",
          "on-background-medium": "var(--danger-on-background-medium)",
          "on-background-strong": "var(--danger-on-background-strong)",
        },
        warning: {
          "background-weak": "var(--warning-background-weak)",
          "background-medium": "var(--warning-background-medium)",
          "background-strong": "var(--warning-background-strong)",
          "solid-weak": "var(--warning-solid-weak)",
          "solid-medium": "var(--warning-solid-medium)",
          "solid-strong": "var(--warning-solid-strong)",
          "on-solid-weak": "var(--warning-on-solid-weak)",
          "on-solid-medium": "var(--warning-on-solid-medium)",
          "on-solid-strong": "var(--warning-on-solid-strong)",
          "border-weak": "var(--warning-border-weak)",
          "border-medium": "var(--warning-border-medium)",
          "border-strong": "var(--warning-border-strong)",
          "alpha-weak": "var(--warning-alpha-weak)",
          "alpha-medium": "var(--warning-alpha-medium)",
          "alpha-strong": "var(--warning-alpha-strong)",
          "on-background-weak": "var(--warning-on-background-weak)",
          "on-background-medium": "var(--warning-on-background-medium)",
          "on-background-strong": "var(--warning-on-background-strong)",
        },
        success: {
          "background-weak": "var(--success-background-weak)",
          "background-medium": "var(--success-background-medium)",
          "background-strong": "var(--success-background-strong)",
          "solid-weak": "var(--success-solid-weak)",
          "solid-medium": "var(--success-solid-medium)",
          "solid-strong": "var(--success-solid-strong)",
          "on-solid-weak": "var(--success-on-solid-weak)",
          "on-solid-medium": "var(--success-on-solid-medium)",
          "on-solid-strong": "var(--success-on-solid-strong)",
          "border-weak": "var(--success-border-weak)",
          "border-medium": "var(--success-border-medium)",
          "border-strong": "var(--success-border-strong)",
          "alpha-weak": "var(--success-alpha-weak)",
          "alpha-medium": "var(--success-alpha-medium)",
          "alpha-strong": "var(--success-alpha-strong)",
          "on-background-weak": "var(--success-on-background-weak)",
          "on-background-medium": "var(--success-on-background-medium)",
          "on-background-strong": "var(--success-on-background-strong)",
        },
        code: {
          moss: "var(--code-moss)",
          gray: "var(--code-gray)",
          aqua: "var(--code-aqua)",
          green: "var(--code-green)",
          blue: "var(--code-blue)",
          violet: "var(--code-violet)",
          orange: "var(--code-orange)",
        },
        static: {
          white: "var(--static-white)",
          "white-medium": "var(--static-white-medium)",
          black: "var(--static-black)",
          "black-medium": "var(--static-black-medium)",
          transparent: "var(--static-transparent)",
        },
      },
      spacing: {
        "0": "var(--static-space-0)",
        "1": "var(--static-space-1)",
        "2": "var(--static-space-2)",
        "4": "var(--static-space-4)",
        "8": "var(--static-space-8)",
        "12": "var(--static-space-12)",
        "16": "var(--static-space-16)",
        "20": "var(--static-space-20)",
        "24": "var(--static-space-24)",
        "32": "var(--static-space-32)",
        "40": "var(--static-space-40)",
        "48": "var(--static-space-48)",
        "56": "var(--static-space-56)",
        "64": "var(--static-space-64)",
        "72": "var(--static-space-72)",
        "80": "var(--static-space-80)",
        "104": "var(--static-space-104)",
        "128": "var(--static-space-128)",
        "160": "var(--static-space-160)",
        xs: "var(--responsive-space-xs)",
        s: "var(--responsive-space-s)",
        m: "var(--responsive-space-m)",
        l: "var(--responsive-space-l)",
        xl: "var(--responsive-space-xl)",
      },
      fontFamily: {
        heading: ["var(--font-heading)", "sans-serif"],
        body: ["var(--font-body)", "sans-serif"],
        code: ["var(--font-code)", "monospace"],
        label: ["var(--font-label)", "sans-serif"],
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        s: "var(--shadow-s)",
        m: "var(--shadow-m)",
        l: "var(--shadow-l)",
        xl: "var(--shadow-xl)",
      },
      transitionDuration: {
        "micro-short": "var(--transition-duration-micro-short)",
        "micro-medium": "var(--transition-duration-micro-medium)",
        "micro-long": "var(--transition-duration-micro-long)",
        "macro-short": "var(--transition-duration-macro-short)",
        "macro-medium": "var(--transition-duration-macro-medium)",
        "macro-long": "var(--transition-duration-macro-long)",
      },
      transitionProperty: {
        "micro-short": "all var(--transition-duration-micro-short) ease",
        "micro-medium": "all var(--transition-duration-micro-medium) ease",
        "micro-long": "all var(--transition-duration-micro-long) ease",
        "macro-short": "all var(--transition-duration-macro-short) ease",
        "macro-medium": "all var(--transition-duration-macro-medium) ease",
        "macro-long": "all var(--transition-duration-macro-long) ease",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeInBottom: {
          from: {
            opacity: "0",
            transform: "translateY(4rem)",
          },
          to: {
            opacity: "1",
            transform: "translateY(0)",
          },
        },
        fadeInTop: {
          from: {
            opacity: "0",
            transform: "translateY(-4rem)",
          },
          to: {
            opacity: "1",
            transform: "translateY(0)",
          },
        },
        pulse: {
          "0%": {
            transform: "scale(0)",
            opacity: "1",
          },
          "100%": {
            transform: "scale(1)",
            opacity: "0",
          },
        },
        shineDefault: {
          "0%": { left: "-100%" },
          "1%": { left: "-100%", opacity: "1" },
          "15%": { left: "100%", opacity: "1" },
          "16%": { opacity: "0" },
          "100%": { left: "-100%" },
        },
        shineHover: {
          "0%": { left: "-100%" },
          "1%": { left: "-100%", opacity: "1" },
          "45%": { left: "100%", opacity: "1" },
          "46%": { opacity: "0" },
          "100%": { left: "-100%" },
        },
        skeleton: {
          "0%": {
            backgroundColor: "var(--neutral-background-strong)",
          },
          "50%": {
            backgroundColor: "var(--neutral-background-medium)",
          },
          "100%": {
            backgroundColor: "var(--neutral-background-strong)",
          },
        },
        spin: {
          "0%": {
            transform: "rotate(0deg)",
            animationTimingFunction: "cubic-bezier(0.5, 0.2, 0.7, 0.5)",
            opacity: "0",
          },
          "80%": {
            opacity: "1",
          },
          "100%": {
            transform: "rotate(360deg)",
            animationTimingFunction: "cubic-bezier(0.5, 0.2, 0.7, 0.5)",
            opacity: "0",
          },
        },
      },
      animation: {
        fadeIn: "fadeIn 0.2s ease-in-out",
        fadeInBottom: "fadeInBottom 0.3s ease-out forwards",
        fadeInTop: "fadeInTop 0.3s ease-out forwards",
        pulse: "pulse 2s infinite ease-out",
        shineDefault: "shineDefault 9s ease-in-out infinite",
        shineHover: "shineHover 3s ease-in-out infinite",
        skeleton: "skeleton 1.5s infinite",
        spin: "spin 1.5s infinite",
      },
    },
  },
  safelist: [
    {
      pattern:
        /^(bg|text|border)-(page|surface|brand|neutral|accent|info|danger|warning|success|code|static)(-.+)?$/,
      variants: ["xs", "s", "m", "l", "xl", "hover", "focus", "active"],
    },
    {
      pattern:
        /^(p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr|gap|gap-x|gap-y|top|right|bottom|left|w|h|min-w|min-h|max-w|max-h)-(0|1|2|4|8|12|16|20|24|32|40|48|56|64|72|80|104|128|160|xs|s|m|l|xl|full|fit|auto|screen)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern:
        /^rounded(-(t|r|b|l|tl|tr|br|bl))?-(none|xs|s|m|l|xl|full|xs-nest-4|xs-nest-8|s-nest-4|s-nest-8|m-nest-4|m-nest-8|l-nest-4|l-nest-8|xl-nest-4|xl-nest-8)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern: /^shadow-(xs|s|m|l|xl|none)$/,
      variants: ["xs", "s", "m", "l", "xl", "hover"],
    },
    {
      pattern: /^(flex|grid|inline-flex|inline-grid|hidden|block|inline|inline-block)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern:
        /^flex-(row|col|row-reverse|col-reverse|wrap|nowrap|wrap-reverse|1|auto|initial|none)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern:
        /^(justify|items|self)-(start|end|center|between|around|evenly|stretch|baseline|auto)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern: /^(grid-cols|grid-rows)-(1|2|3|4|5|6|7|8|9|10|11|12|none|subgrid)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern: /^(col-span|row-span)-(1|2|3|4|5|6|7|8|9|10|11|12|full)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern: /^opacity-(0|10|20|30|40|50|60|70|80|90|100)$/,
      variants: ["xs", "s", "m", "l", "xl", "hover"],
    },
    {
      pattern: /^overflow(-(x|y))?-(auto|hidden|clip|visible|scroll)$/,
      variants: ["xs", "s", "m", "l", "xl"],
    },
    {
      pattern: /^pointer-events-(none|auto|all)$/,
    },
    {
      pattern:
        /^cursor-(default|pointer|not-allowed|interactive|wait|text|move|grab|grabbing|col-resize|row-resize)$/,
    },
    {
      pattern:
        /^transition-(micro-short|micro-medium|micro-long|macro-short|macro-medium|macro-long)$/,
    },
  ],
  plugins: [],
};

export default config;
